---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mas-mongo-ce
spec:
  members: 3
  type: ReplicaSet
  security:
    tls:
      enabled: true
      certificateKeySecretRef:
        name: mas-mongo-ce-cert-secret
      caConfigMapRef:
        name: mas-mongo-ce-cert-map
    authentication:
      modes: ["SCRAM-SHA-1", "SCRAM-SHA-256"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mas-mongo-ce-admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: dbOwner 
          db: admin
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: mas-mongo-ce-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: snappy
    net.tls.allowInvalidCertificates: true
    net.tls.allowInvalidHostnames: true
  statefulSet:
    spec:
      serviceName: mas-mongo-ce-svc
      selector: {}
      template:
        spec:
          containers:
          - name: mongod
            image: quay.io/ibmmas/mongo@sha256:8c48baa1571469d7f5ae6d603b92b8027ada5eb39826c009cb33a13b46864908
            resources:
              limits:
                cpu: "{{MAS_MONGOD_CPU}}"
                memory: "{{MAS_MONGOD_MEM_GB}}"
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "{{MONGODB_STORAGE_CLASS}}"
            resources:
              requests:
                storage: "{{MAS_MONGOD_STORAGE_GB}}"
        - metadata:
            name: logs-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "{{MONGODB_STORAGE_CLASS}}"
            resources:
              requests:
                storage: "{{MAS_MONGOD_STORAGE_LOGS_GB}}"

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: mas-mongo-ce-admin-password
type: Opaque
stringData:
  password: {{MAS_MONGO_PASSWORD}}